name: Build Docker development container

on:
  push:
    branches:
    - master
    - main
    - "build-docker"
    tags:
    - '*'
    - '!v*'

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: IF-THEN-ELSE
        run: |
          if [[ "$(npm view @signalk/server-admin-ui-dependencies version)" ==  "$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' packages/server-admin-ui-dependencies/package.json)" ]]; then
            cd packages/server-admin-ui-dependencies
            npm install --package-lock-only
            npm ci && npm cache clean --force
            # npm publish --access public
          fi
