name: Build official docker release container

on:
  push:
    branches:
    - master
    tags:
    - 'v*'

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kgustafs/signalk-server-docker-official
          tag-sha: false # Do not add git short SHA as Docker tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set TAG for build-args
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile_rel
          platforms: linux/amd64
          push: true
          images: signalk/signalk-server-docker-official
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            TAG=${{ steps.vars.outputs.tag:1 }}
