name: Build official docker release container

on:
  push:
    tags:
    - 'v*'

jobs:
  server-admin-ui-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          if [[ "$(npm view @signalk/server-admin-ui-dependencies version)" !=  "$(awk '/"version":/{gsub(/("|",)/,"",$2);print $2}' ./packages/server-admin-ui-dependencies/package.json)" ]]; then
            echo "Building nmp"
          fi

  server-admin-ui:
    runs-on: ubuntu-latest
    needs: server-admin-ui-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          if [[ "$(npm view @signalk/server-admin-ui version)" !=  "$(awk '/"version":/{gsub(/("|",)/,"",$2);print $2}' ./packages/server-admin-ui/package.json)" ]]; then
            echo "Building nmp"
          fi

  server-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          if [[ "$(npm view @signalk/server-api version)" !=  "$(awk '/"version":/{gsub(/("|",)/,"",$2);print $2}' ./packages/server-api/package.json)" ]]; then
            echo "Building nmp"
          fi

  streams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          if [[ "$(npm view @signalk/streams version)" !=  "$(awk '/"version":/{gsub(/("|",)/,"",$2);print $2}' packages/streams/package.json)" ]]; then
            echo "Building nmp"
          fi

  signalk-server:
    runs-on: ubuntu-latest
    needs: [server-admin-ui, server-api, streams]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set TAG for build-args
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/*/} | sed 's/v//g')
            - name: Show variables
        run:  |
          echo "nmp TAG = ${{ steps.vars.outputs.tag }}"
      - run: |
          if [[ "$(npm view signalk-server version)" !=  "$(awk '/"version":/{gsub(/("|",)/,"",$2);print $2}' package.json)" ]]; then
            echo "Building nmp"
          fi
          if [[ "${{ steps.vars.outputs.tag }}" == *beta* ]]; then
            echo "Tag has BETA in it"
          fi

  docker_image:
    runs-on: ubuntu-latest
    needs: signalk-server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kgustafs/signalk-server-docker
          tag-sha: false # Do not add git short SHA as Docker tag
      - name: Set TAG for build-args
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/*/} | sed 's/v//g')
      - name: Show variables
        run:  |
          echo "TAGS = ${{ steps.docker_meta.outputs.tags }}"
          echo "Build TAG = ${{ steps.vars.outputs.tag }}"
