name: Build official docker release container

on:
  push:
    tags:
    - 'v*'

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kgustafs/signalk-server-docker-official
          tag-sha: false # Do not add git short SHA as Docker tag
      - name: Set TAG for build-args
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/*/} | cut -1-) 
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo "TAG ENV = ${{ steps.docker_meta.outputs.tags }}"
          echo "VERSION = $RELEASE_VERSION"

