name: Build Docker container

on:
  push:
    branches:
    - master
    - latest
    - "build-docker"
    tags:
    - '*'

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kgustafs/signalk-server-docker-dev
          tag-sha: true # add git short SHA as Docker tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Show variables
        run: |
          echo "TAGS = ${{ steps.docker_meta.outputs.tags }}"
          echo "GITHUB_REF = ${{ GITHUB_REF }}"        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          images: kgustafs/signalk-server-docker-dev
          tags: ${{ steps.docker_meta.outputs.tags }}
