name: Build official docker release container

on:
  push:
    tags:
    - 'v*'

jobs:
  signalk-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set TAG for build-args
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/*/})
      - name: Show variables
        run:  |
          echo "npm TAG = ${{ steps.vars.outputs.tag }}"
      - run: |
          npm install --package-lock-only
          npm ci && npm cache clean --force
          if [[ "${{ steps.vars.outputs.tag }}" == *beta* ]];
            then
              echo "npm publish --tag beta"
            else
              echo "npm publish --access public"
          fi

  docker_image:
    runs-on: ubuntu-latest
    needs: signalk-server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: kgustafs/signalk-server-docker
          tag-sha: false # Do not add git short SHA as Docker tag
      - name: Set TAG for build-args
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/*/} | sed 's/v//g')
      - name: Show variables
        run:  |
          echo "TAGS = ${{ steps.docker_meta.outputs.tags }}"
          echo "Build TAG = ${{ steps.vars.outputs.tag }}"
